version: '3'
  
services:
  airflow-spotify:
    image: airflow-spotify:latest
    volumes:
      - ./docker:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone

  spotify-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data